### ISSUE TITLE
Malformed response issue

### ISSUE THREAD

**Issue by Mrhyuan** [iamduo/workq#16]
Im using go client go-workq, and go version is 1.10.

example code:

`
	data := map[string]interface{}{"Hello": "World", "Number": 1}
	bytes, _ := json.Marshal(data)

	u4, err := uuid.NewV4()
	if err != nil {
		log.Errorf("Something Went Wrong: %s", err)
		return
	}

	job := &workq.BgJob{
		ID:          u4.String(),
		Name:        "Queue",
		TTL:         60000, // Expire after 60 seconds
		TTR:         2000,  // 5 second time-to-run limit
		Payload:     bytes,
		MaxAttempts: 3, // @OPTIONAL Absolute max num of attempts.
		MaxFails:    3, // @OPTIONAL Absolute max number of failures.
	}
	log.Debug(job)

	go func() {
		time.Sleep(time.Second * 3)
		err := client.Add(job)
		if err != nil {

		}
	}()

	for {
		job, err := client.Lease([]string{"Queue"}, 500)
		log.Debug(job, err)
		if err == nil && job != nil {
			log.Debugf("Leased Job: ID: %s, Name: %s, Payload: %s", job.ID, job.Name, job.Payload)
		}
	}
`

first attempt always returns malformed response error.
2018-03-14 16:56:56.271 [Main.go:61] [Debug] <nil> Malformed response

**Comment by iamduo** [comment]
@Mrhyuan At first glance, I think the problem is that you are calling `client.Add(job)` in a goroutine within the background while trying to lease the job immediately within the loop below on the same client connection. Each client is bound to only a single connection so the commands/responses are getting crossed in your case. 

Try removing the goroutine func and do the client calls in order:

```
err := client.Add(job)
job, err := client.Lease([]string{"Queue"}, 500)
```

If you actually need have jobs being added concurrently, just use a different client for `Add` vs `Lease`.  Let me know if you have a specific goal in mind and I can help give you a more precise example.

**Comment by Mrhyuan** [comment]
After using two separate clients, it seems everything is ok. Thx!
