### ISSUE TITLE
Change default priority

### ISSUE THREAD

**Issue by sheerun** [iamduo/workq#5]
Hey,

Just letting you know that setting default priority to 0 is not the best idea, as it prevents from creating low-priority jobs with default settings. I saw other framework to change such default to 1000 (I don't remember which one).

So one solution is to set default priority to 1000 while the other is to allow negative priorities.

**Comment by iamduo** [comment]
sheerun,
This is a valid concern and a good idea. Allowing negative ideas is clearer and more natural. In addition the priority at the moment is obnoxiously high at 2**32 and unnecessary. I will flip this into a int32 instead of the current uint32. I'll keep this open until a PR has been merged.

Thanks!

**Comment by iamduo** [comment]
Negative priorities are now in the master branch with tests & docs updated (@see referenced commit). Thanks for the input.
